### ISSUE TITLE
when is "sm64dsonlien " gonna be a thing

### ISSUE THREAD

**Issue by mightymariomanlol** [pants64DS/Goop-Demo#1]
hello, remmeber sm64dsonline, i want it to be here, when is it gonna be here, any updates, any application or build on it or any mentions
, pls tell me

**Comment by pants64DS** [comment]
![image](https://user-images.githubusercontent.com/58012953/139152324-95d26dcd-c9d2-4353-a2c5-02d7d0c67b83.png)

There hasn't been any progress on it for a while because I've been working on other things, *such as this project which is completely unrelated to it*. Please ask any further questions in the [Discord](https://discord.gg/NRfrYbm) rather than here.
