### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by MiikaMatias** [pants64DS/Goop-Demo#2]
Project downloaded 19th of February, 16:55

-Testing reports are clear and the tests cover basically everything.
-Specification documents are as clear as the substance matter allows, while not remaining overtly technical
-Due to its nature the project has a lot of specific mathematics that I am unable to comment on
-I may be confused due to me using poetry for the first time but after running the install command, I failed to be able to run vector tests due to missing 'util' module; same applied to curve_test.py for 'geometry'. Adding these tests to dependency management may be useful.
-Running the program works fine to the point where documented, however I'd be curious to know why the program defines the following position as 'Outside', and is the definition correct? Right now it appears that 'inside' is defined in a way I don't quite understand.
![image](https://user-images.githubusercontent.com/100348027/219958563-78ce4bc9-4d5b-46ba-b972-d9f23cec3184.png)
-The project does, at least for my eyes, look to be quite far from the point of the described paint simulation. Do you think you'll be able to finish it in time? 
-Otherwise the code is clean and the project looks fruitful! Nice job :)

**Comment by pants64DS** [comment]
Thanks for the feedback!

I should probably mention in the documentation that the "inside vs outside" algorithm only needs to work with non-self-intersecting curves, and it doesn't consider points of self-intersection to "close" the curve. In that screenshot, a ray starting at the cursor intersects with the loop an even number of times, and hence it's considered to start outside of the curve. You may also try to visualize the curve as the projection of a thin, curved but continuous strip in 3D space, which makes it intuitively clear why certain regions inside the projection are not actually part of the strip, at least to me. For reference:

![image](https://user-images.githubusercontent.com/39012306/220172182-24877c3f-88f0-4f6d-838c-bcb6549e7025.png)

Either way, it doesn't really matter since the full algorithm only deals with loops that don't intersect themselves.

Last week it did it indeed look like the project was pretty far from the goal, but I've made a lot of progress since then and the main feature / end goal, i.e. the merging of loops, already works to an extent. The tests you mentioned seem to work as well, that might have been an oversight in a specific commit.
